#!/bin/bash

#./processHistogramsInSteps.sh "data/" "data/" false false -1 "data/"
#./processHistogramsInStepsPp.sh "data/" "data/" false false -1
#./processHistogramsInStepsAsymmetry.sh "data/" "data/" false false -1 "data/"
#./processHistogramsInStepsAsymmetryPp.sh "data/" "data/" false false -1

./processHistogramsInStepsAsymmetryPp.sh "data/ppMC2017_RecoReco_Pythia8_pfJets_wtaAxis_noUncorr_dijetWeight_thirdJetCut_JECv4_preprocessed_2019-12-04.root" "data/ppMC2017_RecoReco_Pythia8_pfJets_wtaAxis_noUncorr_dijetWeight_thirdJetCut_JECv4_onlySeagull_processed_2019-12-04.root" false false -1
./processHistogramsInStepsAsymmetryPp.sh "data/ppMC2017_RecoReco_Pythia8_pfJets_wtaAxis_noUncorr_dijetWeight_thirdJetCut_includeThirdJet_JECv4_preprocessed_2019-12-04.root" "data/ppMC2017_RecoReco_Pythia8_pfJets_wtaAxis_noUncorr_dijetWeight_thirdJetCut_includeThirdJet_JECv4_onlySeagull_processed_2019-12-04.root" false false -1
./processHistogramsInStepsAsymmetryPp.sh "data/ppMC2017_RecoReco_Pythia8_pfJets_wtaAxis_noUncorr_dijetWeight_thirdJetCut_noThirdJet_JECv4_preprocessed_2019-12-04.root" "data/ppMC2017_RecoReco_Pythia8_pfJets_wtaAxis_noUncorr_dijetWeight_thirdJetCut_noThirdJet_JECv4_onlySeagull_processed_2019-12-04.root" false false -1

#./processHistogramsInSteps.sh "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_improvisedMixingFromSubeNon0_xjBins_sube0_wtaAxis_noCorrections_processed_JECv6_2019-09-26.root" "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_improvisedMixingFromSubeNon0_xjBins_sube0_wtaAxis_onlyJffCorrection_jffExplore_processed_JECv6_2019-11-26.root" true false -1 "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_improvisedMixing_xjBins_subeNon0_wtaAxis_JECv6_preprocessed_2019-09-26.root"

#./processHistogramsInStepsAtHighPt.sh "data/PbPbMC2018_RecoReco_akFlowPuCs4PFJet_noUncorr_5eveMix_preprocessed_2019-10-07.root" "data/PbPbMC2018_RecoReco_akFlowPuCs4PFJet_noUncOrInc_5eveMix_onlySeagullAndTracking_workInProgress_mixingScale16_processed_2019-10-07.root" false false -1 

#./processHistogramsInSteps.sh "data/PbPbMC2018_RecoReco_akFlowPuCs4PFJet_noUncorr_5eveMix_onlySeagull_processed_2019-11-19.root" "data/PbPbMC2018_RecoReco_akFlowPuCs4PFJet_noUncorr_5eveMix_seagullAndTracking_processed_2019-11-20.root" false false -1 "data/"

#./processHistogramsInSteps.sh "data/PbPbMC2018_RecoReco_akFlowPuCs4PFJet_noUncorr_5eveMix_preprocessed_2019-10-07.root" "data/PbPbMC2018_RecoReco_akFlowPuCs4PFJet_noUncorr_5eveMix_allCorrections_tunedTracking_testOfUpdate_processed_2019-11-26.root" true true -1 "data/"

#./processHistogramsInSteps.sh "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_improvisedMixing_wtaAxis_JECv6_preprocessed_2019-09-26.root" "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_mixingFromSubeNon0AtLowPt_newTry_wtaAxis_JECv6_noCorrections_processed_2019-09-26.root" false false -1 "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_improvisedMixing_xjBins_subeNon0_wtaAxis_JECv6_preprocessed_2019-09-26.root"

#./processHistogramsInStepsAtHighPt.sh "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_improvisedMixing_wtaAxis_JECv6_preprocessed_2019-09-26.root" "data/PbPbMC_RecoGen_akFlowPuCs4PFJet_noUncorr_mixingFromSubeNon0AtLowPt_newTry_wtaAxis_JECv6_noCorrections_processed_2019-09-26.root" false false -1
